"""Breakdown_log models fix name

Revision ID: 1feff76347b6
Revises: 98959f3cedb1
Create Date: 2024-06-02 12:12:45.364618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1feff76347b6'
down_revision: Union[str, None] = '98959f3cedb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_electricity_object',
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['electricity_object.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], )
    )
    op.drop_table('worker_object')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_object',
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['electricity_object.id'], name='worker_object_object_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name='worker_object_worker_id_fkey')
    )
    op.drop_table('worker_electricity_object')
    # ### end Alembic commands ###
